version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todolist"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yk8eix4xbbcc"
s3_prefix = "todolist"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
