pipeline {
    agent any
    stages {
        stage('Trigger: Staging') {
            steps {
                echo '// You have triggered the staging downstream job'
                
            }
        }
    }
}