pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                deleteDir()
                echo '// Checkout // Get some code from a CodeCommit repository'
                git branch: 'dev', credentialsId: '676655fc-c40f-4964-b3ba-c3dfb91b2094', url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/todo-list-aws'
            }
        }
        stage('SetUp'){
            steps{
                echo '// SetUp // Creating Python Virtual Environment'
                sh '''
                    python3 -m venv env
                    source env/bin/activate 
                    pip install -r requirements.txt -q

                    python3 -m venv unitenv
                    source unitenv/bin/activate
                    pip install -r ./test/requirements.txt -q
                '''
            }
        }
        stage('Testing'){
            steps{
                echo '// Testing // Static analysis of code'
                sh '''
                    source env/bin/activate
                    
                    rm ./radon/*
                    radon cc src/ --min ${RADON_MIN} --total-average -s --json --output-file ./radon/analysis.json
                    grep -il 'rank' ./radon/* && 'Radon test: failed'

                    rm ./flake8/*
                    flake8 src/ --exit-zero --ignore ${FLAKE8_IGNORE} --statistics --show-source --format=pylint --output-file ./flake8/analysis.json
                    grep -il -E '[[:alnum:]]' ./flake8/* && 'Flake8 test: failed'
                    
                    rm ./bandit/*
                    bandit src/* --exit-zero --format txt --output ./bandit/analysis.txt
                    grep -il 'No issues identified' ./bandit/* || 'Bandit test: failed!'
                '''
                echo '// Testing // Unittest of app'
                sh '''
                    source unitenv/bin/activate
                    coverage run -m TestToDoClass
                    coverage html --fail-under=80 todolist.py                     
                '''
            }
        }
        stage('Build'){
            steps{
                sh 'sam build -u'
            }
        }
        stage('Deploy'){
            steps{
                sh 'sam deploy --config-env staging'
            }
        }

    }       
}
